dataset_info = dict(
    dataset_name='weinreb15pt',
    paper_info=dict(
        author='',
        title='',
        container='',
        year='',
        homepage='',
    ),
    keypoint_info={
        0: dict(name='spine_low', id=0, color=[173, 160, 183], type='lower', swap=''),
        1: dict(name='tail_base', id=1, color=[173, 160, 183], type='lower', swap=''),
        2: dict(name='tail_tip', id=2, color=[173, 160, 183], type='lower', swap=''),
        3: dict(name='spine_mid', id=3, color=[173, 160, 183], type='lower', swap=''),
        4: dict(name='spine_high', id=4, color=[173, 160, 183], type='lower', swap=''),
        5: dict(name='left_ear', id=5, color=[120, 184, 181], type='upper', swap='right_ear'),
        6: dict(name='right_ear', id=6, color=[120, 184, 181], type='upper', swap='left_ear'),
        7: dict(name='forehead', id=7, color=[120, 184, 181], type='upper', swap=''),
        8: dict(name='nose_tip', id=8, color=[120, 184, 181], type='upper', swap=''),
        9: dict(name='left_fore_paw', id=9, color=[232, 85, 95], type='upper', swap='right_fore_paw'),
        10: dict(name='right_fore_paw', id=10, color=[169, 201, 30], type='upper', swap='left_fore_paw'),
        11: dict(name='left_hind_paw_back', id=11, color=[247, 173, 0], type='lower', swap='right_hind_paw_back'),
        12: dict(name='left_hind_paw_front', id=12, color=[247, 173, 0], type='lower', swap='right_hind_paw_front'),
        13: dict(name='right_hind_paw_back', id=13, color=[0, 92, 93], type='lower', swap='left_hind_paw_back'),
        14: dict(name='right_hind_paw_front', id=14, color=[0, 92, 93], type='lower', swap='left_hind_paw_front'),
    },
    skeleton_info={
        0: dict(link=('tail_tip', 'tail_base'), id=0, color=[173, 160, 183]),
        1: dict(link=('tail_base', 'spine_low'), id=1, color=[173, 160, 183]),
        2: dict(link=('spine_low', 'spine_mid'), id=2, color=[173, 160, 183]),
        3: dict(link=('spine_mid', 'spine_high'), id=3, color=[173, 160, 183]),
        4: dict(link=('spine_high', 'left_ear'), id=4, color=[120, 184, 181]),
        5: dict(link=('spine_high', 'right_ear'), id=5, color=[120, 184, 181]),
        6: dict(link=('spine_high', 'forehead'), id=6, color=[120, 184, 181]),
        7: dict(link=('forehead', 'nose_tip'), id=7, color=[120, 184, 181]),
        8: dict(link=('left_hind_paw_back', 'left_hind_paw_front'), id=8, color=[247, 173, 0]),
        9: dict(link=('spine_low', 'left_hind_paw_back'), id=9, color=[247, 173, 0]),
        10: dict(link=('right_hind_paw_back', 'right_hind_paw_front'), id=10, color=[0, 92, 93]),
        11: dict(link=('spine_low', 'right_hind_paw_back'), id=11, color=[0, 92, 93]),
        12: dict(link=('spine_high', 'left_fore_paw'), id=12, color=[232, 85, 95]),
        13: dict(link=('spine_high', 'right_fore_paw'), id=13, color=[169, 201, 30]),
    },
    upper_body_ids = [4, 5, 6, 7, 8, 9, 10],
    lower_body_ids = [0, 1, 2, 3, 11, 12, 13, 14],
    joint_weights = [1.0] * 15,
    sigmas = [1.0] * 15,
)

parents_dict = {
    "nose_tip": "forehead",
    "left_ear": "spine_high",
    "right_ear": "spine_high",
    "forehead": "spine_high",
    "left_fore_paw": "spine_high",
    "right_fore_paw": "spine_high",
    "left_hind_paw_front": "left_hind_paw_back",
    "right_hind_paw_front": "right_hind_paw_back",
    "left_hind_paw_back": "spine_low",
    "right_hind_paw_back": "spine_low",
    "tail_base": "spine_low",
    "spine_low": "spine_mid",
    "spine_mid": "spine_high",
}